
name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

   
  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

  Deployment:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Autres étapes de construction de votre application

      - name: Deploy locally and generate result file
        run: |
          mkdir -p D:\dep    # Créer le répertoire de destination
          scp -r D:\dep  > deployment_result.txt  # Copier les fichiers et enregistrer les résultats dans un fichier
        continue-on-error: true  # Permet de continuer même si la commande de déploiement échoue

      - name: Upload deployment result
        uses: actions/upload-artifact@v2
        with:
          name: deployment-result
          path: deployment_result.txt  # Télécharger le fichier résultat du déploiement


